dataset:
  - path: 'data/source'
    sub:
      - path: 'cornell'
        task: 'cornell'
      - path: 'daily'
        task: 'daily'

processed:
  path: 'data/processed'

task: 'daily'

gpu: '2'

model:
  save_path: 'save'
  current: 'auto-attn'

hyperparameter:
  embedding_size: 64
  n_layers: 2
  max_sent_length: 15
  min_frequency: 2
  hidden_size: 512
  dropout: 0.9
  n_sampled: 1024

train:
  epoch: 25
  learning_rate: 0.002
  print_interval: 50
  save_interval: 200
  batch_size: 256
